---
- name: install timezone data
  apt:
    name: tzdata
    state: present
  when: ansible_os_family == "Debian"

- name: install timezone data
  yum:
    name: tzdata
    state: present
  when: ansible_os_family == "RedHat"

- name: set system timezone to {{timezone}}
  copy:
    dest: /etc/timezone
    content: "{{timezone}}\n"
    owner: root
    group: root
    mode: 0644

- name: set current timezone to {{timezone}}
  copy:
    src: /usr/share/zoneinfo/{{timezone}}
    dest: /etc/localtime
