---
- name: set hostname
  hostname:
    name: "{{ hostname }}"
  when: hostname is defined
  tags: ['hostname']

- name: add hostname to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^{{ ansible_default_ipv4.address | regex_escape }}'
    insertafter: '^127\.0\.0\.1 '
    line: "{{ ansible_default_ipv4.address }} {{ hostname }} {{ hostname.split('.')[0] }}"
    state: present
  when: hostname is defined
  tags: ['hostname']

# @todo: remove after all environments are provisioned
- name: remove old hostname from /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.1\.1'
    state: absent
  when: hostname is defined
  tags: ['hostname']
