---
- name: deploy common roles on global ubuntu hosts
  hosts:
    - vault.global.pkn-afc-engineering.com
    - deploy.global.pkn-afc-engineering.com
    - nexus.global.pkn-afc-engineering.com
    - backup-nexus.global.pkn-afc-engineering.com
    - ext-reverse.global.pkn-afc-engineering.com
    - debian.global.pkn-afc-engineering.com
    - jama-jira-connector.global.pkn-afc-engineering.com
    - ldaps.pkn-afc-engineering.com
    - ldaps-group.pkn-afc-engineering.com
    - jenkins-aws.global.pkn-afc-engineering.com
    - nat-gateway.global.pkn-afc-engineering.com
    - openvpn.global.pkn-afc-engineering.com
    - pritunl.global.pkn-afc-engineering.com
    - mattermost.global.pkn-afc-engineering.com
    - matterwarrior.global.pkn-afc-engineering.com
    - monitoring.global.pkn-afc-engineering.com
    - jira.global.pkn-afc-engineering.com
    - sto-ovh.global.pkn-afc-engineering.com
    - ejbca.global.pkn-afc-engineering.com
    - jira.global.pkn-afc-engineering.com
    - code-server.global.pkn-afc-engineering.com
    - builder-swap.global.pkn-afc-engineering.com
    - jira-attachment-transfer.global.pkn-afc-engineering.com
    - monitoring-data.global.pkn-afc-engineering.com
    - grafana.global.pkn-afc-engineering.com
    - dispatch.global.pkn-afc-engineering.com
  become: yes
  user: ubuntu
  ignore_errors: yes
  roles:
    - { role: common, tags: ['common'] }
    - { role: users, tags: ['users'] }


- name: renew certificate for global vms
  hosts:
  - nexus.global.pkn-afc-engineering.com
  - ext-reverse.global.pkn-afc-engineering.com
  - debian.global.pkn-afc-engineering.com
  - jenkins-aws.global.pkn-afc-engineering.com
  - mattermost.global.pkn-afc-engineering.com
  - ldaps.pkn-afc-engineering.com
  - matterwarrior.global.pkn-afc-engineering.com
  become: yes
  user: ubuntu
  roles:
  - { role: certbot_renewal, tags: ['certbot_renewal'] }


- name: deploy vault ssh keys
  hosts:
     - vault.global.pkn-afc-engineering.com
  become: yes
  user: ubuntu
  vars:
    vault_server_config:
      listener:
        tcp:
          address: 127.0.0.1:8200
          tls_disable: true
      storage:
        file:
          path: "{{ vault_server_home }}/data"
  roles:
    - { role: vault-server, tags: ['vault'] }

- name: Install pritunl
  hosts:
    - pritunl.global.pkn-afc-engineering.com
  become: yes
  user: ubuntu
  roles:
    - { role: pritunl, tags: ['pritunl'] }


- name: deploy deploy machine
  hosts:
     - deploy.global.pkn-afc-engineering.com
  become: yes
  user: ubuntu
  roles:
    - {role: deploy, tags: ['deploy'] }

- name: deploy ejbca machine
  hosts:
    - ejbca.global.pkn-afc-engineering.com
  become: yes
  user: ubuntu
  vars:
    metricbeat_tags: '["global","immortal", "aws"]'
  roles:
    - {role: ejbca, tags: ['ejbca'] }
    - { role: metricbeat, tags: ['common'] }



- name: deploy or update Nexus
  hosts:
     - nexus.global.pkn-afc-engineering.com
  become: yes
  user: ubuntu
  vars:
    telegraf_organization: "flowbird-influx"
    telegraf_bucket: "global"
    tags:
      - name: env
        value: global
      - name: group
        value: immortal
    nexus_heap_size: 4G
    nexus_version: 3.21.2-03
    nexus_direct_memory_size: 6717M
    volumes:
      - device: /dev/xvdd
        partition: /dev/xvdd1
        mountpoint: /var/lib/nexus/blobs/npm-hosted
        fstype: ext4
        options: noatime
      - device: /dev/xvde
        partition: /dev/xvde1
        mountpoint: /var/lib/nexus/blobs/maven2-hosted
        fstype: ext4
        options: noatime
      - device: /dev/xvdf
        partition: /dev/xvdf1
        mountpoint: /var/lib/nexus/blobs/binary-hosted
        fstype: ext4
        options: noatime
      - device: /dev/xvdg
        partition: /dev/xvdg1
        mountpoint: /var/lib/nexus/blobs/docker-hosted
        fstype: ext4
        options: noatime
      - device: /dev/xvdh
        partition: /dev/xvdh1
        mountpoint: /data
        fstype: ext4
        options: noatime
      - device: /dev/xvdi
        partition: /dev/xvdi1
        mountpoint: /var/lib/nexus/blobs/helsinki-hosted
        fstype: ext4
        options: noatime
      - device: /dev/xvdj
        partition: /dev/xvdj1
        mountpoint: /var/lib/nexus/blobs/android-hosted
        fstype: ext4
        options: noatime
      - device: /dev/xvdl
        partition: /dev/xvdl1
        mountpoint: /var/lib/nexus/blobs/sss-docker-hosted
        fstype: ext4
        options: noatime
  roles:
    - { role: telegraf, tags: ['common'] }
    - { role: node, tags: ['node'] }
    - { role: nexus, tags: ['nexus'] }
    - { role: nexus-nginx, tags: ['nexus-nginx'] }
#    - { role: volumes, tags: ['volumes'] }

- name: deploy or update Reverse Proxy
  hosts:
    - ext-reverse.global.pkn-afc-engineering.com
  become: yes
  user: ubuntu
  vars:
    telegraf_organization: "flowbird-influx"
    telegraf_bucket: "global"
    tags:
      - name: env
        value: global
      - name: group
        value: vital
    virtualHosts:
      - serverName: ext-nexus.global.pkn-afc-engineering.com
        proxiedUrl: http://nexus.global.pkn-afc-engineering.com:8081/
    ip_white_list:
      - ip: "61.5.212.97/32"
  roles:
    - { role: telegraf, tags: ['common'] }
    - { role: reverse-proxy-apache, tags: ['reverse'] }


- name: deploy or update Debian repository
  hosts:
    - debian.global.pkn-afc-engineering.com
  become: yes
  user: ubuntu
  vars:
    nexus_version: 3.21.2-03
  roles:
    -  {role: node, tags: ['node'] }
    - { role: nexus, tags: ['nexus'] }
    - { role: nexus-generic-nginx, tags: ['nexus'] }
    - { role: certbot, tags: ['nexus'] }


- name: deploy jama-jira-connector machine
  hosts:
     - jama-jira-connector.global.pkn-afc-engineering.com
  become: yes
  user: ubuntu
  roles:
    - { role: jama-jira-connector, tags: ['jama'] }


- name: deploy ldaps machine
  hosts:
    - ldaps.pkn-afc-engineering.com
  become: yes
  user: ubuntu
  vars:
    telegraf_organization: "flowbird-influx"
    telegraf_bucket: "global"
    tags:
      - name: env
        value: global
      - name: group
        value: immortal
  roles:
    - { role: ldap, tags: ['ldap'] }
    - { role: telegraf, tags: ['common'] }
  #    - { role: reverse-proxy-apache, tags: ['reverse'] }
  #    - { role: certbot, tags: ['certbot'] }


- name: deploy ldaps-group machine
  hosts:
    - ldaps-group.pkn-afc-engineering.com
  become: yes
  user: ubuntu
  vars:
    telegraf_organization: "flowbird-influx"
    telegraf_bucket: "global"
    tags:
      - name: env
        value: global
      - name: group
        value: immortal
  roles:
    - { role: ldap, tags: ['ldap'] }
    - { role: telegraf, tags: ['common'] }


- name: deploy ldap-ui machine
  hosts:
    - ldap-ui.pkn-afc-engineering.com
  become: yes
  user: ubuntu
  vars:
    ldap_ui_pwd_min_length: 12
    ldap_ui_pwd_max_length: 35
    ldap_ui_pwd_min_lower: 0
    ldap_ui_pwd_min_upper: 1
    ldap_ui_pwd_min_digit: 1
    ldap_ui_reset_url: https://ldap-ui.pkn-afc-engineering.com
  roles:
    - { role: common, tags: ['common', 'ldap-poc'] }
#    - { role: ldap-ui, tags: ['ldap', 'ldap-ui', 'ldap-poc'] }
    - { role: users, tags: ['users','ldap-poc'] }
    - { role: sudoer_no_pwd, tags: ['sudoer','ldap-poc'] }


- name: deploy Jenkins-aws machine
  hosts:
    - jenkins-aws.global.pkn-afc-engineering.com
  become: yes
  user: ubuntu
  vars:
    telegraf_organization: "flowbird-influx"
    telegraf_bucket: "global"
    tags:
      - name: env
        value: global
      - name: group
        value: immortal
  vars_files:
  - vars/vaultfile.yml
  roles:
  - { role: telegraf, tags: ['common'] }
  - { role: awscli, tags: ['awscli'] }
  - { role: terraform, tags: ['terraform'] }
  - { role: certbot, tags: ['certbot'] }
  - { role: jenkins-nginx, tags: ['jenkins'] }
  - { role: git-lfs, tags: ['git-lfs'] }
  #- { role: jenkins, tags: ['jenkins'] }


- name: deploy nat-gateway machine
  hosts:
    - nat-gateway.global.pkn-afc-engineering.com
  become: yes
  user: ubuntu
  roles:
    - { role: port-forward, tags: ['nat'] }


- name: mattermost
  hosts:
    - mattermost.global.pkn-afc-engineering.com
  become: yes
  user: ubuntu
  vars:
    volumes:
    - device: /dev/nvme1n1
      device_real_name: /dev/sdd
      mountpoint: /var/lib/mattermost
      fstype: ext4
      options: noatime
  roles:
  - { role: volumes-nvme, tags: ['volumes'] }
  - { role: mattermost, tags: ['mattermost'] }
  - { role: certbot, tags: ['certbot'] }


- name: matterwarrior
  hosts:
  - matterwarrior.global.pkn-afc-engineering.com
  become: yes
  user: ubuntu
  vars:
    virtualHosts:
    - serverName: matterwarrior.global.pkn-afc-engineering.com
      proxiedUrl: https://matterwarrior.global.pkn-afc-engineering.com/
    ip_white_list:
    - ip: "61.5.212.97/32"
  roles:
  - { role: certbot, tags: ['certbot'] }

- name: code-server
  hosts:
    - code-server.global.pkn-afc-engineering.com
  become: yes
  user: ubuntu
  vars:
  roles:
    - { role: certbot, tags: ['certbot'] }
    - { role: code-server, tags: ['code'] }
    - { role: code-server-nginx, tags: ['code'] }


- name: prometheus
  hosts:
    - prometheus.global.pkn-afc-engineering.com
  become: yes
  user: ubuntu
  vars:
    telegraf_organization: "flowbird-influx"
    telegraf_bucket: "global"
    tags:
      - name: env
        value: global
      - name: group
        value: immortal
  roles:
    - { role: common, tags: ['common'] }
    - { role: users, tags: ['users'] }
    - { role: docker, tags: ['docker'] }

- name: grafana
  hosts:
    - grafana.global.pkn-afc-engineering.com
  become: yes
  user: ubuntu
  vars:
    telegraf_organization: "flowbird-influx"
    telegraf_bucket: "global"
    tags:
      - name: env
        value: global
      - name: group
        value: immortal
  roles:
    - { role: grafana, tags: ['grafana'] }
    - { role: telegraf, tags: ['common'] }


- name: monitoring-data
  hosts:
    - monitoring-data.global.pkn-afc-engineering.com
  become: yes
  user: ubuntu
  vars:
    telegraf_organization: "flowbird-influx"
    tags:
      - name: env
        value: global
      - name: group
        value: immortal
  roles:
    - { role: influxDB, tags: ['influxdb'] }
    - { role: prometheus, tags: ['prometheus'] }
    - { role: telegraf, tags: ['common'] }

- name: dispatch
  hosts:
    - dispatch.global.pkn-afc-engineering.com
  become: yes
  user: ubuntu
  vars:
    jenkins_location_admin: it-afc@parkeon.com
    jenkins_location_url: http://jenkins.product-pkn.pkn-afc-engineering.com:8080
    jenkins_java_args:
      - -Dhudson.model.DirectoryBrowserSupport.CSP=
  roles:
    - { role: jenkins, tags: ['jenkins'] }
    - { role: certbot, tags: ['certbot'] }
    - { role: jenkins-nginx, tags: ['certbot'] }
    - { role: git-lfs, tag: ['git'] }

